export { typographyConfig } from './typography';
export { backgroundConfig } from './background';
export { borderAndShadowConfig } from './border-and-shadow';
export { effectsConfig } from './effects';
export { spacingConfig } from './spacing';
export { positionConfig } from './position';
export { sizeConfig } from './size';
export { layoutConfig } from './layout';
export { iconConfig } from './icon';
