export const layoutConfig = {
	publisherDisplay: true,
	publisherFlexDirection: true,
	publisherAlignItems: true,
	publisherJustifyContent: true,
	publisherGap: true,
	publisherFlexWrap: true,
	publisherAlignContent: true,
	publisherGridAlignItems: true,
	publisherGridJustifyItems: true,
	publisherGridAlignContent: true,
	publisherGridJustifyContent: true,
	publisherGridGap: true,
	publisherGridDirection: true,
	publisherGridColumns: true,
	publisherGridRows: true,
	publisherGridAreas: true,
};
