export const typographyConfig = {
	publisherFontSize: true,
	publisherLineHeight: true,
	publisherFontColor: true,
	publisherTextShadow: true,
	publisherTextAlign: true,
	publisherTextDecoration: true,
	publisherFontStyle: true,
	publisherTextTransform: true,
	publisherDirection: true,
	publisherLetterSpacing: true,
	publisherWordSpacing: true,
	publisherTextIndent: true,
	publisherTextOrientation: true,
	publisherTextColumns: true,
	publisherTextStrokeColor: true,
	publisherWordBreak: true,
};
