// @flow

/**
 * External dependencies
 */
import { __ } from '@wordpress/i18n';

/**
 * Blockera dependencies
 */
import { Icon } from '@blockera/icons';
import { generalInnerBlockStates } from '../../../extensions/libs/block-card/block-states/states';

/**
 * Internal dependencies
 */
import type { InnerBlockModel } from '../../../extensions/libs/block-card/inner-blocks/types';

export const inners: InnerBlockModel = {
	'elements/before': {
		name: 'elements/before',
		label: __('Before', 'blockera'),
		description: __(
			'Creates an inline pseudo-element before the block content.',
			'blockera'
		),
		icon: <Icon library="blockera" icon="blockera" iconSize="20" />,
		settings: {
			force: false,
			priority: 10,
			hasContent: true,
		},
		availableBlockStates: generalInnerBlockStates,
	},
	'elements/after': {
		name: 'elements/after',
		label: __('After', 'blockera'),
		description: __(
			'Creates an inline pseudo-element after the block content.',
			'blockera'
		),
		icon: <Icon library="blockera" icon="blockera" iconSize="20" />,
		settings: {
			force: false,
			priority: 10,
			hasContent: true,
		},
		availableBlockStates: generalInnerBlockStates,
	},
	'elements/marker': {
		name: 'elements/marker',
		label: __('Marker Pseudo-Elements', 'blockera'),
		description: __(
			'Styles the marker generated by the browser for lists.',
			'blockera'
		),
		icon: <Icon library="blockera" icon="blockera" iconSize="20" />,
		settings: {
			force: false,
			priority: 35,
		},
		availableBlockStates: generalInnerBlockStates,
	},
	'elements/placeholder': {
		name: 'elements/placeholder',
		label: __('Placeholder', 'blockera'),
		description: __(
			'Styles the placeholder text visible until content is entered.',
			'blockera'
		),
		icon: <Icon library="blockera" icon="blockera" iconSize="20" />,
		settings: {
			force: false,
			priority: 35,
		},
		availableBlockStates: generalInnerBlockStates,
	},
};
