/**
 * Border-radius preset canvas preview usages — keep aligned with `BorderRadius` extension consumer.
 */
export const BORDER_RADIUS_PRESET_PREVIEW_USAGE_ALL = 'all' as const;
export const BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_LEFT = 'topLeft' as const;
export const BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_RIGHT = 'topRight' as const;
export const BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_LEFT =
	'bottomLeft' as const;
export const BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_RIGHT =
	'bottomRight' as const;

export type BorderRadiusPresetPreviewUsage =
	| typeof BORDER_RADIUS_PRESET_PREVIEW_USAGE_ALL
	| typeof BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_LEFT
	| typeof BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_RIGHT
	| typeof BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_LEFT
	| typeof BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_RIGHT;

export const BORDER_RADIUS_PRESET_PREVIEW_USAGES =
	new Set<BorderRadiusPresetPreviewUsage>([
		BORDER_RADIUS_PRESET_PREVIEW_USAGE_ALL,
		BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_LEFT,
		BORDER_RADIUS_PRESET_PREVIEW_USAGE_TOP_RIGHT,
		BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_LEFT,
		BORDER_RADIUS_PRESET_PREVIEW_USAGE_BOTTOM_RIGHT,
	]);

export const DEFAULT_BORDER_RADIUS_PRESET_PREVIEW_USAGE =
	BORDER_RADIUS_PRESET_PREVIEW_USAGE_ALL;
