<?php

use Publisher\Framework\Illuminate\Foundation\ValueAddon\DynamicValue\Fields;

return [
	'post-id'              => Fields\PostID::class,
	'post-url'             => Fields\PostURL::class,
	'site-url'             => Fields\SiteURL::class,
	'post-time'            => Fields\PostTime::class,
	'site-logo'            => Fields\SiteLogo::class,
	'user-info'            => Fields\UserInfo::class,
	'post-date'            => Fields\PostDate::class,
	'post-terms'           => Fields\PostTerms::class,
	'post-title'           => Fields\PostTitle::class,
	'shortcode'            => Fields\Shortcode::class,
	'site-title'           => Fields\SiteTitle::class,
	'author-url'           => Fields\AuthorURL::class,
	'page-title'           => Fields\PageTitle::class,
	'author-info'          => Fields\AuthorInfo::class,
	'author-meta'          => Fields\AuthorMeta::class,
	'author-name'          => Fields\AuthorName::class,
	'site-tag-line'        => Fields\SiteTagline::class,
	'internal-url'         => Fields\InternalURL::class,
	'comments-url'         => Fields\CommentsURL::class,
	'archive-meta'         => Fields\ArchiveMeta::class,
	'post-excerpt'         => Fields\PostExcerpt::class,
	'archive-link'         => Fields\ArchiveLink::class,
	'post-gallery'         => Fields\PostGallery::class,
	'archive-title'        => Fields\ArchiveTitle::class,
	'comments-number'      => Fields\CommentsNumber::class,
	'post-custom-field'    => Fields\PostCustomField::class,
	'current-data-time'    => Fields\CurrentDateTime::class,
	'request-parameter'    => Fields\RequestParameter::class,
	'featured-image-data'  => Fields\FeaturedImageData::class,
	'post-featured-image'  => Fields\PostFeaturedImage::class,
	'author-profile-image' => Fields\AuthorProfileImage::class,
	'user-profile-picture' => Fields\UserProfilePicture::class,
	'archive-desc'         => Fields\ArchiveDescription::class,
];
