export default function OriginBottomLeft() {
	return (
		<svg
			width="19"
			height="18"
			viewBox="0 0 19 18"
			xmlns="http://www.w3.org/2000/svg"
		>
			<g clipPath="url(#clip0_2501_18187)">
				<rect x="0.5" y="13" width="5" height="5" rx="2.5" />
				<rect
					opacity="0.3"
					x="7.5"
					y="14"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="7.5"
					y="2"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="7.5"
					y="8"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="13.5"
					y="8"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="1.5"
					y="2"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="1.5"
					y="8"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="13.5"
					y="14"
					width="3"
					height="3"
					rx="1.5"
				/>
				<rect
					opacity="0.3"
					x="13.5"
					y="2"
					width="3"
					height="3"
					rx="1.5"
				/>
			</g>
			<defs>
				<clipPath id="clip0_2501_18187">
					<rect width="18" height="18" transform="translate(0.5)" />
				</clipPath>
			</defs>
		</svg>
	);
}
