#!/usr/bin/env sh
# Edit packages/global-packages/packages/dev-tools/root-configs/.husky/commit-msg
# project:bootstrap copies this to the host .husky/ folder.

commit_message="$1"
# exit with a non zero exit code incase of an invalid commit message

# use git-conventional-commits, see https://github.com/qoomon/git-conventional-commits
# Config source of truth: @blockera/dev-tools (synced via global-packages).
node_modules/git-conventional-commits/cli.js commit-msg-hook \
	--config packages/global-packages/packages/dev-tools/git-conventional-commits.yaml \
	"$commit_message"
