name: 'Shared setup action'
description: 'shared configuration for workflow will be done.'
inputs:
    host:
        description: 'submodule host address'
        required: false
    private-key:
        description: 'access to submodule with private key'
        required: true

runs:
    using: 'composite'
    steps:
        - name: Setup SSH
          uses: MrSquaare/ssh-setup-action@v1

        - name: Clone Submodule
          shell: bash
          run: |
              cd libs
              git clone git@github.com:publisherwp/storybook.git
          with:
              host: github.com
              private-key: ${{ inputs.private-key }}

        - name: Setup Node.js and install dependencies
          uses: ./.github/setup-node
