name: Build Blockera Plugin Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build_tests:
        name: Building and Run E2E Tests (PHP ${{ matrix.php }})
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera' || github.event_name == 'pull_request' }}
        strategy:
            fail-fast: true
            matrix:
                php: ['7.4', '8.0', '8.1', '8.2']
        env:
            BLOCKERA_GLOBAL_PACKAGES_TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.BLOCKERABOT_PAT }}

            - name: Ensure global-packages submodule
              uses: ./.github/actions/ensure-global-packages

            - uses: ./packages/global-packages/packages/dev-tools/github/actions/build-plugin-zip-tests
              with:
                  php-version: ${{ matrix.php }}
