name: Code Lint

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    lint:
        name: Code lint
        if: ${{ github.repository == 'blockeraai/blockera' || github.event_name == 'pull_request' }}
        uses: blockeraai/blockera-global-packages/.github/workflows/consumer-code-lint.yml@62823172fad194c7621d583b6683a6d3923b09a7
        secrets:
            BLOCKERABOT_PAT: ${{ secrets.BLOCKERABOT_PAT }}
        with:
            config-path: .github/blockera-ci.json
