name: Cypress Components Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

jobs:
    cypress_components_tests:
        name: Cypress Components Tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'publisherwp/publisher-core' || github.event_name == 'pull_request' }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Shared Setup Action
              uses: ./.github/shared-setup
              with:
                  host: github.com
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Run Cypress Tests
              run: npm run test:ct
