name: JavaScript Unit Tests (By Jest)

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    unit-js:
        name: JavaScript
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera' || github.event_name == 'pull_request' }}

        strategy:
            fail-fast: false
            matrix:
                node: ['18.3.0']

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
              with:
                  token: ${{ secrets.BLOCKERABOT_PAT }}

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node
              with:
                  global-packages-token: ${{ secrets.BLOCKERABOT_PAT }}
                  node-version: ${{ matrix.node }}

            - name: Jest unit tests
              uses: ./packages/global-packages/packages/dev-tools/github/actions/jest-unit-tests
              with:
                  config-path: .github/blockera-ci.json
