name: Storybook Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'publisherwp/publisher-core' || github.event_name == 'pull_request' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Install Storybook
              run: npx storybook@latest

            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v1
              with:
                  host: github.com
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Clone Submodule
              run: |
                  cd libs
                  git clone git@github.com:publisherwp/storybook.git

            - name: Build Storybook
              run: npm run storybook:build --quiet --debug-webpack
            - name: Serve Storybook and run tests
              run: |
                  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                  "npx http-server storybook-static --port 6006 --silent" \
                  "npx wait-on tcp:6006 && yarn test-storybook"
