name: Sync Packages to Other Repos on Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    sync-packages:
        name: Sync Packages to Other Repos
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.sha }}

            - name: Check if .pr-sync-env.json exists
              id: check-sync-file
              run: |
                  if [ -f .pr-sync-env.json ]; then
                      echo "sync-file-exists=true" >> $GITHUB_OUTPUT
                  else
                      echo "sync-file-exists=false" >> $GITHUB_OUTPUT
                  fi

            - name: Read sync configuration
              if: steps.check-sync-file.outputs.sync-file-exists == 'true'
              id: read-sync-config
              run: |
                  BASE_BRANCH=$(cat .pr-sync-env.json | jq -r '.baseBranch')
                  IN_SYNC_BRANCH=$(cat .pr-sync-env.json | jq -r '.inSyncBranch')
                  INTO_REPOSITORY=$(cat .pr-sync-env.json | jq -r '.intoRepository')
                  echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
                  echo "inSyncBranch=$IN_SYNC_BRANCH" >> $GITHUB_OUTPUT
                  echo "intoRepository=$INTO_REPOSITORY" >> $GITHUB_OUTPUT

            - name: Sync packages with other dependent repositories
              if: steps.check-sync-file.outputs.sync-file-exists == 'true'
              uses: blockeraai/blockera-folder-sync@v1.0.0
              with:
                  BASE_BRANCH: ${{ steps.read-sync-config.outputs.baseBranch }}
                  CREATE_SYNC_BRANCH: ${{ steps.read-sync-config.outputs.inSyncBranch }}
                  STATIC_REPOSITORY: ${{ steps.read-sync-config.outputs.intoRepository }}
                  TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
                  USERNAME: ${{ secrets.BLOCKERABOT_USERNAME }}
                  EMAIL: ${{ secrets.BLOCKERABOT_EMAIL }}
