name: Sync Packages to Other Repos on Push in Master

on:
    push:
        branches:
            - master

jobs:
    sync-packages:
        name: Sync Packages to Other Repos
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Sync packages with other dependent repositories
              uses: blockeraai/blockera-folder-sync@v1.0.0
              with:
                  TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
                  USERNAME: ${{ secrets.BLOCKERABOT_USERNAME }}
                  EMAIL: ${{ secrets.BLOCKERABOT_EMAIL }}
