name: Sync Packages to Other Repos

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    sync-packages:
        name: Sync Packages to Other Repos
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' || github.event_name == 'push'

        steps:
            - name: Checkout Primary Repo
              uses: actions/checkout@v4

            - name: Check if .pr-sync-env.json exists
              id: check-sync-file
              if: github.event_name == 'pull_request'
              run: |
                  if [ -f .pr-sync-env.json ]; then
                      echo "sync-file-exists=true" >> $GITHUB_OUTPUT
                  else
                      echo "sync-file-exists=false" >> $GITHUB_OUTPUT
                  fi

            - name: Read sync configuration
              if: steps.check-sync-file.outputs.sync-file-exists == 'true' && github.event_name == 'pull_request'
              id: read-sync-config
              run: |
                  BASE_BRANCH=$(cat .pr-sync-env.json | jq -r '.baseBranch')
                  IN_SYNC_BRANCH=$(cat .pr-sync-env.json | jq -r '.inSyncBranch')
                  INTO_REPOSITORY=$(cat .pr-sync-env.json | jq -r '.intoRepository')
                  echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
                  echo "inSyncBranch=$IN_SYNC_BRANCH" >> $GITHUB_OUTPUT
                  echo "intoRepository=$INTO_REPOSITORY" >> $GITHUB_OUTPUT

            - name: Sync packages with other dependent repositories
              if: (github.event_name == 'pull_request' && steps.check-sync-file.outputs.sync-file-exists == 'true') || github.event_name == 'push'
              uses: blockeraai/blockera-folder-sync@v1.0.0
              with:
                  BASE_BRANCH: ${{ steps.read-sync-config.outputs.baseBranch }}
                  CREATE_SYNC_BRANCH: ${{ steps.read-sync-config.outputs.inSyncBranch }}
                  STATIC_REPOSITORY: ${{ steps.read-sync-config.outputs.intoRepository }}
                  TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
                  USERNAME: ${{ secrets.BLOCKERABOT_USERNAME }}
                  EMAIL: ${{ secrets.BLOCKERABOT_EMAIL }}
