name: Test JavaScript

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    jest:
        name: Unit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: ./.github/setup-node

            - name: Run tests
              run: npm run test:js
