name: Jest

on:
    pull_request:
        branches:
            - master

jobs:
    jest:
        name: Unit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: ./.github/setup-node

            - name: Run tests
              run: npm run test:js
