name: Unit Tests
run-name: ${{ github.actor }} Run Unit Tests Jobs ✅

# Since Unit Tests are required to pass for each PR,
# we cannot disable them for documentation-only changes.
on:
    pull_request:
    push:
        branches:
            - main
            - 'release/**'
            - 'publisherwp/**'
    # Allow manually triggering the workflow.
    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    submodule-update:
        name: Git Submodule Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Initialize Submodule
              run: git submodule init

    unit-js:
        name: JavaScript
        runs-on: ubuntu-latest
        needs: [submodule-update]
        if: ${{ github.repository == 'publisherwp/publisher-core' || github.event_name == 'pull_request' }}

        strategy:
            fail-fast: false
            matrix:
                node: ['14']

        steps:
            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node
              with:
                  node-version: ${{ matrix.node }}

            - name: Npm build
              run: npx run build

            - name: Running the tests
              run: npm run test:js
